---
features:
  - |
    Issuing a SIGHUP (e.g. ``pkill -HUP ironic-neutron-agent``) to the agent
    service will cause the service to reload and use any changed values for
    *mutable* configuration options.

    Mutable configuration options are indicated as such in the `sample
    configuration file <https://docs.openstack.org/networking-baremetal/latest/configuration/sample-config.html>`_
    by ``Note: This option can be changed without restarting``.

    A warning is logged for any changes to immutable configuration options.
